### PR TITLE
Add new wallet options

### PR DESCRIPTION
**Pull request by hamidroohi92**
This fixes new wallets supports and also closed issue No.46

### CODE REVIEW

**Comment by hackfisher** [comment]
Issue #46 seems not fixed.

I'm good to merge this first if you are going to fix #46 separately.

**Comment by hackfisher** [comment]
image
Another issue for USDT (Darwinia, AssetHub Polkadot), can not call and wake metamsk:

**Comment by hackfisher** [comment]
DOT (Assethub Polkadot -> Darwinia) balance should be 0.01 DOT, but showing zero:

image
image

**Comment by hackfisher** [comment]
Please note that in Polkadot XCM transferred tokens, there are two common used token standards:

First one is assets(used by Assethub Polkadot, and Darwinia): https://github.com/paritytech/polkadot-sdk/tree/master/substrate/frame/assets

Anothe one is xtoken(used by Hydration): https://github.com/open-web3-stack/open-runtime-module-library/tree/master/xtokens

This might result reading data from different pallets storage using rpc, adation/integration config might be needed here. Your can refere the first version before UI changes.

**Comment by hamidroohi92** [comment]
Darwinia Address: 0x96bB28c2771c67FA5cA479A6316fa123198826a4
          needed token: usdt, dot, pink
Polkadot address: 5G74vnykgW1bzhVVdjAK74WKpEEKZNmN9fYzmrbohF5jrLra
          needed token: dot
Hydration adress: 7NSAyEfhR7dgP9A1g1hUz3dmaPnDyyBKGYEUKHH5rZeDqNF2
          needed token: hdx

**Comment by boundless-forest** [comment]
image

image

I attempted to transfer from the Darwinia chain to Hydration(vercel-b105c8c), but the warning seems incorrect; it has nothing to do with the Polkadot AssetHub, and the send button is unavailable. I have no idea why.

**Review by hackfisher — APPROVED** [review]

**Pull request merged**
