### PR TITLE
New Design and Flow changes

### PR DESCRIPTION
**Pull request by nblogist**
Introduces new design and flow changes.

### CODE REVIEW

**Comment by hamidroohi71** [comment]
I am working to fix all the following contents:

- [x] Add new design UI components
- [x] Fix design for mobile
- [x] Add interactivity to the UI elements
- [x] Fix remaining items from the UI design
- [x] Fix the design for wallet connection modal
- [x] Fix the wallet connection process
- [x] Fix the wallet data reading in the header and transfer inputs
- [x] Fix the token mapping between the sender and recipient
- [x] Fix the input address logic for both sender and recipient 
- [x] Fix modals reading data
- [x] Fix final transaction step
- [x] Fix the chain and wallet switch when selected chain changed
- [x] Change the chain selection in the way match tokens
- [x] Add  Motions
- [x] Handle wallet address change in sender input
- [x] Control the styles and functionality in mobile and tablet
- [ ] Review the code for possible bugs
- [ ] Remove the unused components

**Comment by nblogist** [comment]
Will let Fnunkuy check out the issue with deployment. so vivian can get a vercel link to view.

**Comment by hackfisher** [comment]
> Will let Fnunkuy check out the issue with deployment. so vivian can get a vercel link to view.

@fewensa Would you please help diagnostic the cause for the failure of deployment?

**Comment by nblogist** [comment]
Hey guys this is more or less ready - we are running some tests and fine tuning some edges this week but we can start taking a look at this.

**Comment by hackfisher** [comment]
@1022ranji and @boundless-forest Please help test and feedback.

**Comment by DreUncle** [comment]
https://www.figma.com/design/OseMkyZivJbottjf6GcXlr/APPS?node-id=16035-4054&t=dPgrar76iAPAZ2Qv-0
I have made a unified process, please use the chain&token logo here to replace the existing one

**Comment by hackfisher** [comment]
@1022ranji I'am not sure if the supported wallets to connect is in the scope of this improvement.

But following wallets and wallet connect are definitely to be supported:


image
image


Reference:

https://apps.moonbeam.network/moonbeam/xcm?asset=dot

**Comment by 1022ranji** [comment]
### ParaLink Test & Feedback @nblogist @hamidroohi71 
Test version: https://crosschain-l9cithmgp-itering.vercel.app/

- [ ] Can not read my balance
image

- [x] Spell wrong (you --> your)
image

- [x] There is an inconsistency in the capitalization style used in the prompt messages on the page. Please update to:

> Please connect to your wallet
> Please enter the recipient address
> Please enter the amount
image

- [x] The address “Copy” button doesn’t work

image

- [ ] Could you optimize the 'Connect Wallet' section? Please refer to: https://apps.moonbeam.network/moonbeam/staking

image

**Comment by nblogist** [comment]
Thank you for your feedback @1022ranji ! Interesting to see that it isn't showing your balance - but it is for me 
image

CC @hamidroohi71 

Looking into rest of the parts!

**Comment by nblogist** [comment]
image
- [x] Drop down is hiding

image
- [x] Is this supposed to be animated?

image
- [ ] Details link isn't clickable

I don't see ring show up [here](https://hydration.subscan.io/custom_token?unique_id=asset_registry%2F8e10d9f1d511efdb3938b0d1ace5982c4e212da5&tab=transfers) but that might take some time - so wil check again in a few mins

image

- [ ] Chain Link isn't clickable now
CC @hamidroohi71

**Comment by 1022ranji** [comment]
@nblogist Could we aim to finalize this pull request by the end of this week and release a new version? That way, we can make progress on the RingDAO Vote issue https://github.com/darwinia-network/vote.ringdao.com/issues/4.

**Comment by hackfisher** [comment]
> @nblogist Could we aim to finalize this pull request by the end of this week and release a new version? That way, we can make progress on the RingDAO Vote issue [darwinia-network/vote.ringdao.com#4](https://github.com/darwinia-network/vote.ringdao.com/issues/4).

If there are difficulties, we can first release a viable and functional version, and address the remaining issues later.

**Comment by hamidroohi71** [comment]
> > @nblogist Could we aim to finalize this pull request by the end of this week and release a new version? That way, we can make progress on the RingDAO Vote issue [darwinia-network/vote.ringdao.com#4](https://github.com/darwinia-network/vote.ringdao.com/issues/4).
> 
> If there are difficulties, we can first release a viable and functional version, and address the remaining issues later.

Hi. Actually, we were done at the end of last week. But adding the new wallets according to Raji's comment make us in a way to put much more effort into implementing 9 new wallets with app. It's the reason of why it's taking longer again.

**Comment by hamidroohi71** [comment]
If you want I can finalize it without this feature and release it and then after doing other tasks, I willl work on new wallet design and implementations.

**Comment by hackfisher** [comment]
> If you want I can finalize it without this feature and release it and then after doing other tasks, I willl work on new wallet design and implementations. 

LGTM

**Comment by 1022ranji** [comment]
> > If you want I can finalize it without this feature and release it and then after doing other tasks, I willl work on new wallet design and implementations.
> 
> LGTM

@nblogist @hamidroohi71 All features are functioning now except for the wallet. I suggest we finalize and release this version first, and then address the remaining wallet issues after completing https://github.com/darwinia-network/vote.ringdao.com/issues/4.

**Review by 1022ranji — APPROVED** [review]

**Pull request merged**
